### ISSUE TITLE
US1: Accès page d'acceuil

### ISSUE THREAD

**Issue by Sora952** [WildCodeSchool/lyon-js-03-20-p2-g2#3]
- **_ User Storie :_** 

> _En tant qu'utilisateur, je voudrais avoir accès à une page d'accueil claire et visuelle afin de visualiser directement le service qui va m'être rendu._

- **_-Critères de validations :_**

> Une image background avec le logo et l'explication claire du service rendu.

- **_Scénarios de tests envisagés :_**

 > 1. Je me rends sur le site
 > 2. La page d'accueil  s'affiche sur mon écran

**Comment by ComicScrip** [comment]
Merci de rajouter les labels donnés dans le cours https://docs.google.com/presentation/d/1TMnp6a89yA099Gryuh9iizx9OcHQVW96gWmkMWuYXKA/edit#slide=id.g72fcf98ae0_0_54 à la slide 6, comme demandé la semaine dernière...
